### ISSUE TITLE
Sprint 9 (Priorities)

### ISSUE THREAD

**Issue by Sahas664** [AppBoxTech/veel-design#40]
```[tasklist]
### Tasks
- [x] Email template design once an enterprise business user submits "Request for Demo" form.
- [x] Email template design once an enterprise business user submits "Contact-Us" form.
- [x] Landing page and Mobile Landing design content and design finalization.
- [x] Payments Screen
- [x] Shipping Address for Content Creators/Users
- [x] Campaign detail view
- [ ] https://github.com/AppBoxTech/veel-design/issues/41
- [x] Add "General Tab" in Notification Section of Enterprise, (Just above the campaign)
- [x] Add a info message in the payments upgrade and downgrade action modal so that enterprise business user knows what happens while upgrading or downgrading their current plan so that enterprise business user can take a informed decision.
- [x] Enhance the feedback form desgin
- [x] content of "Take a tour: Creators"
- [x] Help and Support Content Confirmation with Dileep dai.
- [x] Campaign status enhancements for users
- [ ] Visual bug hunting for Ios App on test fligt
```
```[tasklist]
### Tasks
```
