### ISSUE TITLE
Sprint 10:

### ISSUE THREAD

**Issue by Sahas664** [AppBoxTech/veel-design#48]
Doing: 

- [x] screen dimensions for App Store and play store 

to do: 

- [x] Veel banner for twitter"X", fb, Linkedin 

Content creators: 

- [x] 1) add YT, Instagram, TIktok link to profile.  Design it 

- [x] 2)redo content creators flow. profile video ko intro haru lai kata rakhne this section and content inside "my profile" should  be redesigned.
- [x]  content creator cannot sign up from outside of USA. payments section ma we need to add message that we are not available there. 
```[tasklist]
### Tasks
```
