### ISSUE TITLE
Sprint 11

### ISSUE THREAD

**Issue by Sahas664** [AppBoxTech/veel-design#49]
```[tasklist]
### Tasks
- [x] we also need to design the payment tab that has some generic message for the users (outside of US) (p0)
- [x] Design the error wireframe where: As a content creator I should not be able to upload more than 5 videos in a campaign.
- [x] Design the error wireframe where: As a content creator I should not be able to upload videos of more than 500 MB in size.
- [x] Pricing page responsive (p0)
- [x] font change for iOS and android app. Roboto for android and SF for iOS. set baseline for it (p1)
- [x] Adding CTA for the video player : 1. Information 2. Report the video 3. Block 4. Follow/Unfollow
- [x] Add a consent form for asking user to locally store the data.
- [x] As a Veel content moderator, I should be able to revisit the contents reported by users so that I can re-confirm that the content complies with the Veel guidelines.
- [x] Design responsive for order summary page
- [x] Design a graphic for empty notification section stating "No notifications yet"
- [x] As a content creator/user I should be able to submit an an issue from the more section, so that I do not get disturbed by the floating issue form time and again. (Pragati keep the button name as "Feedback" and just above the logout.)
- [ ] Rethink about the loader that appears in the Mobile app during the loading phase
- [ ] Visual Bug: Team is asking for SVG asset for contact us, mobile app veel logo, for now these assets are apprering blurry in safari.
- [ ] Content creator in enterprise
- [ ] Redesigning wallet page for creators
```

**Comment by pragatiib** [comment]
unchecked tasks is moved to sprint 12
