### ISSUE TITLE
Sprint 12

### ISSUE THREAD

**Issue by Sahas664** [AppBoxTech/veel-design#52]
```[tasklist]
### Tasks
- [x] p0: Design a sticky toast bar for Veel app: As a content creator/user, If I do not turn on my location, then I cannot verify myself to be from USA, in that case App treats such user from outside USA. But if user is from USA but have not turned location then we show this sticky bar, with a note saying, "Hey there! To unlock the full potential of Veel and enjoy videos tailored to your area, please enable location access." and a button Allow
- [x] Design a way for giving content creators rating stars.
- [x] Content creator in enterprise
- [x] Redesigning wallet page for creators
- [x] Create the email template to send to user base whenever multiple rejection tag and remarks is added
- [x] Create a graphics to display over videos which do not have any thumnails
- [x] Veel-mobile-app: Design a graphics whenever there is no campaigns listed in My camapaign list. Suggestion from Dileep dai: ("Let’s change the text to “Video Request” - empty text should have some icon and text is “Currently, there are no video requests.”)"): URL for ticket- https://github.com/AppBoxTech/veel-app/issues/377
- [x] Create a skip button for video moderation section for both cover and content videos so that content moderator can approve/reject such videos later (when they are confused if they should approve or reject videos
- [x] We need a rounded Veel logo to place it in Stipe, see the preview section for the image, also on dark theme email template it is not pleasing to see the veel logo.
- [x] light logo for email dark mode
- [x] Enteprise Chat: Wireframing
- [x] high fidelity chat ui design
- [x] update content of subscription upgrade and downgrade.
- [ ] Let us upgrade the subscription upgrade flow as well.
- [x] Update design for Moderator section so that they can know which content video moderation is to be done, and what is the count of videos where moderation is to be done.
- [ ] Plan consumption
- [ ] Design validation on User directory errors
- [ ] Rethink about the loader that appears in the Mobile app during the loading phase
- [ ] Visual Bug: Team is asking for SVG asset for contact us, mobile app veel logo, for now these assets are apprering blurry in safari.
```

```[tasklist]
### Tasks
```

**Comment by Sahas664** [comment]
![Image](https://github.com/AppBoxTech/veel-design/assets/132865401/bf572bd7-ad0c-4651-9785-e6f60d008e4a)
