### ISSUE TITLE
demo call changes

### ISSUE THREAD

**Issue by pragatiib** [AppBoxTech/veel-design#64]
```[tasklist]
### Tasks
- [x] email and sms template should be vertical.
- [x] change the toast validation to inline validation. remove toast from the veel ecosystem
- [x] remove import csv from group, change the group icon.
```
